title: Crosscover
pkg_name: crosscover
url: http://git.blivesta.com/crosscover/
description: Carousel of a simple background image using jquery and animate.css.
tags: jquery, css, animation, slider
author: blivesta
author_url: http://blivesta.com/
maintainer: ungki
maintainer_url: https://github.com/ungki
copyright: Copyright (c) 2013-2015 blivesta. all rights reserved.
