title: Crosscover
description: Carousel of a simple background image using jquery and animate.css.
tags: jquery, slider, background image
author: blivesta
author_url: https://blivesta.com/
github_url: https://github.com/blivesta
copyright: Copyright (c) 2013-2015 blivesta. all rights reserved.
git_star_btn: http://ghbtns.com/github-btn.html?user=blivesta&amp;repo=crosscover&amp;type=watch&amp;count=true
